### ISSUE TITLE
Countdown skipping values while counting

### ISSUE THREAD

**Issue by diib96** [mw60680/stopwatch#12]
Steps - 

1) Increase the seconds using the "increase" button and keeping the cursor on it so that it automatically increases.
2) Let it go till 90
3) Click on play button.

Don't know why, but it goes down to 36 or something and then starts the countdown.

**Comment by mw60680** [comment]
This is a separate feature where if the seconds or minutes entered is above 60, then it automatically gets converted to minutes.

Like 1 min 90 sec = 2 min 30 sec
